#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/secrets-bridge .
docker build -t ${REPO}/secrets-bridge:${TAG} .

echo Built ${REPO}/secrets-bridge:${TAG}
